# Generated by Django 6.0.5 on 2026-05-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
