# Generated by Django 6.0.5 on 2026-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
    ]
